// <auto-generated />
using System;
using Mateus.SistemaAcademico.DAO;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Mateus.SistemaAcademico.Migrations
{
    [DbContext(typeof(SistemaContext))]
    [Migration("20190730171418_primeira")]
    partial class primeira
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Mateus.SistemaAcademico.Models.Aluno", b =>
                {
                    b.Property<int>("IdAluno")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdPessoa");

                    b.Property<int>("RegistroDoAluno");

                    b.Property<int?>("ResponsavelIdResponsavel");

                    b.Property<int?>("cPFIdCpf");

                    b.Property<int?>("enderecoIdEndereco");

                    b.Property<int?>("nomeIdNome");

                    b.HasKey("IdAluno");

                    b.HasIndex("ResponsavelIdResponsavel");

                    b.HasIndex("cPFIdCpf");

                    b.HasIndex("enderecoIdEndereco");

                    b.HasIndex("nomeIdNome");

                    b.ToTable("Alunos");
                });

            modelBuilder.Entity("Mateus.SistemaAcademico.Models.CPF", b =>
                {
                    b.Property<int>("IdCpf")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Valor");

                    b.HasKey("IdCpf");

                    b.ToTable("CPF");
                });

            modelBuilder.Entity("Mateus.SistemaAcademico.Models.Endereco", b =>
                {
                    b.Property<int>("IdEndereco")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Bairro");

                    b.Property<int>("CEP");

                    b.Property<string>("Complemento");

                    b.Property<string>("Logradouro");

                    b.Property<int>("Numero");

                    b.HasKey("IdEndereco");

                    b.ToTable("Endereco");
                });

            modelBuilder.Entity("Mateus.SistemaAcademico.Models.Nome", b =>
                {
                    b.Property<int>("IdNome")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Dados");

                    b.HasKey("IdNome");

                    b.ToTable("Nome");
                });

            modelBuilder.Entity("Mateus.SistemaAcademico.Models.Responsavel", b =>
                {
                    b.Property<int>("IdResponsavel")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdPessoa");

                    b.Property<int?>("cPFIdCpf");

                    b.Property<int?>("enderecoIdEndereco");

                    b.Property<int?>("nomeIdNome");

                    b.HasKey("IdResponsavel");

                    b.HasIndex("cPFIdCpf");

                    b.HasIndex("enderecoIdEndereco");

                    b.HasIndex("nomeIdNome");

                    b.ToTable("Responsavel");
                });

            modelBuilder.Entity("Mateus.SistemaAcademico.Models.Telefone", b =>
                {
                    b.Property<int>("IdTelefone")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AlunoIdAluno");

                    b.Property<int?>("ResponsavelIdResponsavel");

                    b.Property<int>("Valor");

                    b.HasKey("IdTelefone");

                    b.HasIndex("AlunoIdAluno");

                    b.HasIndex("ResponsavelIdResponsavel");

                    b.ToTable("Telefone");
                });

            modelBuilder.Entity("Mateus.SistemaAcademico.Models.Aluno", b =>
                {
                    b.HasOne("Mateus.SistemaAcademico.Models.Responsavel", "Responsavel")
                        .WithMany()
                        .HasForeignKey("ResponsavelIdResponsavel");

                    b.HasOne("Mateus.SistemaAcademico.Models.CPF", "cPF")
                        .WithMany()
                        .HasForeignKey("cPFIdCpf");

                    b.HasOne("Mateus.SistemaAcademico.Models.Endereco", "endereco")
                        .WithMany()
                        .HasForeignKey("enderecoIdEndereco");

                    b.HasOne("Mateus.SistemaAcademico.Models.Nome", "nome")
                        .WithMany()
                        .HasForeignKey("nomeIdNome");
                });

            modelBuilder.Entity("Mateus.SistemaAcademico.Models.Responsavel", b =>
                {
                    b.HasOne("Mateus.SistemaAcademico.Models.CPF", "cPF")
                        .WithMany()
                        .HasForeignKey("cPFIdCpf");

                    b.HasOne("Mateus.SistemaAcademico.Models.Endereco", "endereco")
                        .WithMany()
                        .HasForeignKey("enderecoIdEndereco");

                    b.HasOne("Mateus.SistemaAcademico.Models.Nome", "nome")
                        .WithMany()
                        .HasForeignKey("nomeIdNome");
                });

            modelBuilder.Entity("Mateus.SistemaAcademico.Models.Telefone", b =>
                {
                    b.HasOne("Mateus.SistemaAcademico.Models.Aluno")
                        .WithMany("Telefone")
                        .HasForeignKey("AlunoIdAluno");

                    b.HasOne("Mateus.SistemaAcademico.Models.Responsavel")
                        .WithMany("Telefone")
                        .HasForeignKey("ResponsavelIdResponsavel");
                });
#pragma warning restore 612, 618
        }
    }
}
