// <auto-generated />
using System;
using Mateus.SistemaAcademico.DAO;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Mateus.SistemaAcademico.Migrations
{
    [DbContext(typeof(SistemaContext))]
    [Migration("20190809185457_PrimeiraMigration")]
    partial class PrimeiraMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Mateus.SistemaAcademico.Endereco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AlunoId");

                    b.Property<string>("Bairro");

                    b.Property<int>("CEP");

                    b.Property<string>("Complemento");

                    b.Property<string>("Logradouro");

                    b.Property<int>("Numero");

                    b.Property<int?>("ProfessorId");

                    b.Property<int?>("ResponsavelId");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId");

                    b.HasIndex("ProfessorId");

                    b.HasIndex("ResponsavelId");

                    b.ToTable("Enderecos");
                });

            modelBuilder.Entity("Mateus.SistemaAcademico.Models.Aluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cpf");

                    b.Property<int?>("CursoId");

                    b.Property<string>("Nome");

                    b.Property<int>("RegistroDoAluno");

                    b.Property<int?>("ResponsaveisId");

                    b.HasKey("Id");

                    b.HasIndex("CursoId");

                    b.HasIndex("ResponsaveisId");

                    b.ToTable("Alunos");
                });

            modelBuilder.Entity("Mateus.SistemaAcademico.Models.Conteudo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descricao")
                        .IsRequired();

                    b.Property<int>("DisciplinaId");

                    b.Property<int>("TipoConteudos");

                    b.HasKey("Id");

                    b.HasIndex("DisciplinaId");

                    b.ToTable("Conteudos");
                });

            modelBuilder.Entity("Mateus.SistemaAcademico.Models.Curso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CoordenadorId");

                    b.Property<DateTime>("DataDeFim");

                    b.Property<DateTime>("DataDeInicio");

                    b.Property<float>("Duracao");

                    b.Property<string>("Nome")
                        .IsRequired();

                    b.Property<int>("TipoCurso");

                    b.HasKey("Id");

                    b.HasIndex("CoordenadorId");

                    b.ToTable("Cursos");
                });

            modelBuilder.Entity("Mateus.SistemaAcademico.Models.Disciplina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("CargaHoraria");

                    b.Property<int>("ConteudoId");

                    b.Property<string>("Nome")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Disciplinas");
                });

            modelBuilder.Entity("Mateus.SistemaAcademico.Models.Frequencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AlunoId");

                    b.Property<DateTime>("Data");

                    b.Property<int>("DisciplinaId");

                    b.Property<int>("TipoFrequencia");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId")
                        .IsUnique();

                    b.HasIndex("DisciplinaId")
                        .IsUnique();

                    b.ToTable("Frequencias");
                });

            modelBuilder.Entity("Mateus.SistemaAcademico.Models.JOINS.CursoDisciplina", b =>
                {
                    b.Property<int>("CursoId");

                    b.Property<int>("DisciplinaId");

                    b.HasKey("CursoId", "DisciplinaId");

                    b.HasIndex("DisciplinaId");

                    b.ToTable("CursoDisciplina");
                });

            modelBuilder.Entity("Mateus.SistemaAcademico.Models.JOINS.ProfessorCurso", b =>
                {
                    b.Property<int>("ProfessorId");

                    b.Property<int>("CursoId");

                    b.HasKey("ProfessorId", "CursoId");

                    b.HasIndex("CursoId");

                    b.ToTable("ProfessorCurso");
                });

            modelBuilder.Entity("Mateus.SistemaAcademico.Models.Professor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cpf");

                    b.Property<int>("DisciplinaId");

                    b.Property<string>("Nome");

                    b.Property<int>("RegistroDoProfessor");

                    b.Property<string>("Titulacao")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("DisciplinaId")
                        .IsUnique();

                    b.ToTable("Professor");
                });

            modelBuilder.Entity("Mateus.SistemaAcademico.Models.Responsavel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cpf");

                    b.Property<string>("Nome");

                    b.HasKey("Id");

                    b.ToTable("Responsaveis");
                });

            modelBuilder.Entity("Mateus.SistemaAcademico.Models.Telefone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AlunoId");

                    b.Property<int>("Numero");

                    b.Property<int?>("ProfessorId");

                    b.Property<int?>("ResponsavelId");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId");

                    b.HasIndex("ProfessorId");

                    b.HasIndex("ResponsavelId");

                    b.ToTable("Telefones");
                });

            modelBuilder.Entity("Mateus.SistemaAcademico.Endereco", b =>
                {
                    b.HasOne("Mateus.SistemaAcademico.Models.Aluno")
                        .WithMany("Enderecos")
                        .HasForeignKey("AlunoId");

                    b.HasOne("Mateus.SistemaAcademico.Models.Professor")
                        .WithMany("Enderecos")
                        .HasForeignKey("ProfessorId");

                    b.HasOne("Mateus.SistemaAcademico.Models.Responsavel")
                        .WithMany("Enderecos")
                        .HasForeignKey("ResponsavelId");
                });

            modelBuilder.Entity("Mateus.SistemaAcademico.Models.Aluno", b =>
                {
                    b.HasOne("Mateus.SistemaAcademico.Models.Curso", "Curso")
                        .WithMany("Alunos")
                        .HasForeignKey("CursoId");

                    b.HasOne("Mateus.SistemaAcademico.Models.Responsavel", "Responsaveis")
                        .WithMany("Aluno")
                        .HasForeignKey("ResponsaveisId");
                });

            modelBuilder.Entity("Mateus.SistemaAcademico.Models.Conteudo", b =>
                {
                    b.HasOne("Mateus.SistemaAcademico.Models.Disciplina", "Disciplina")
                        .WithMany("Conteudo")
                        .HasForeignKey("DisciplinaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Mateus.SistemaAcademico.Models.Curso", b =>
                {
                    b.HasOne("Mateus.SistemaAcademico.Models.Professor", "Coordenador")
                        .WithMany()
                        .HasForeignKey("CoordenadorId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Mateus.SistemaAcademico.Models.Frequencia", b =>
                {
                    b.HasOne("Mateus.SistemaAcademico.Models.Aluno", "Aluno")
                        .WithOne("Frequencia")
                        .HasForeignKey("Mateus.SistemaAcademico.Models.Frequencia", "AlunoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Mateus.SistemaAcademico.Models.Disciplina", "Disciplina")
                        .WithOne("Frequencia")
                        .HasForeignKey("Mateus.SistemaAcademico.Models.Frequencia", "DisciplinaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Mateus.SistemaAcademico.Models.JOINS.CursoDisciplina", b =>
                {
                    b.HasOne("Mateus.SistemaAcademico.Models.Curso", "Curso")
                        .WithMany("Disciplina")
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Mateus.SistemaAcademico.Models.Disciplina", "Disciplina")
                        .WithMany("Curso")
                        .HasForeignKey("DisciplinaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Mateus.SistemaAcademico.Models.JOINS.ProfessorCurso", b =>
                {
                    b.HasOne("Mateus.SistemaAcademico.Models.Curso", "Curso")
                        .WithMany("Professor")
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Mateus.SistemaAcademico.Models.Professor", "Professor")
                        .WithMany("Curso")
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Mateus.SistemaAcademico.Models.Professor", b =>
                {
                    b.HasOne("Mateus.SistemaAcademico.Models.Disciplina", "DisciplinasMinistratadas")
                        .WithOne("Professor")
                        .HasForeignKey("Mateus.SistemaAcademico.Models.Professor", "DisciplinaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Mateus.SistemaAcademico.Models.Telefone", b =>
                {
                    b.HasOne("Mateus.SistemaAcademico.Models.Aluno")
                        .WithMany("Telefones")
                        .HasForeignKey("AlunoId");

                    b.HasOne("Mateus.SistemaAcademico.Models.Professor")
                        .WithMany("Telefones")
                        .HasForeignKey("ProfessorId");

                    b.HasOne("Mateus.SistemaAcademico.Models.Responsavel")
                        .WithMany("Telefones")
                        .HasForeignKey("ResponsavelId");
                });
#pragma warning restore 612, 618
        }
    }
}
