// <auto-generated />
using System;
using Mateus.SistemaAcademico.DAO;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Mateus.SistemaAcademico.Migrations
{
    [DbContext(typeof(SistemaContext))]
    partial class SistemaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Mateus.SistemaAcademico.Endereco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AdministradorId");

                    b.Property<int?>("AlunoId");

                    b.Property<string>("Bairro");

                    b.Property<string>("Cep");

                    b.Property<string>("Cidades");

                    b.Property<string>("Complemento");

                    b.Property<string>("Estados");

                    b.Property<string>("NomeRua");

                    b.Property<int>("Numero");

                    b.Property<int?>("ProfessorId");

                    b.Property<int?>("ResponsavelId");

                    b.Property<int?>("SecretariaId");

                    b.HasKey("Id");

                    b.HasIndex("AdministradorId");

                    b.HasIndex("AlunoId");

                    b.HasIndex("ProfessorId");

                    b.HasIndex("ResponsavelId");

                    b.HasIndex("SecretariaId");

                    b.ToTable("Enderecos");
                });

            modelBuilder.Entity("Mateus.SistemaAcademico.Models.Administrador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cpf")
                        .IsRequired();

                    b.Property<DateTime>("DataDeNascimento");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("Nome")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Administradores");
                });

            modelBuilder.Entity("Mateus.SistemaAcademico.Models.Aluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cpf")
                        .IsRequired();

                    b.Property<int>("CursoId");

                    b.Property<DateTime>("DataDeNascimento");

                    b.Property<int?>("DisciplinaId");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("Nome")
                        .IsRequired();

                    b.Property<int?>("ResponsavelId1");

                    b.HasKey("Id");

                    b.HasIndex("CursoId");

                    b.HasIndex("DisciplinaId");

                    b.HasIndex("ResponsavelId1");

                    b.ToTable("Alunos");
                });

            modelBuilder.Entity("Mateus.SistemaAcademico.Models.Conteudo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descricao")
                        .IsRequired();

                    b.Property<int>("DisciplinaId");

                    b.Property<string>("Nome")
                        .IsRequired();

                    b.Property<int>("TipoConteudos");

                    b.HasKey("Id");

                    b.HasIndex("DisciplinaId");

                    b.ToTable("Conteudos");
                });

            modelBuilder.Entity("Mateus.SistemaAcademico.Models.Curso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Area");

                    b.Property<int>("CoordenadorId");

                    b.Property<DateTime>("DataDeFim");

                    b.Property<DateTime>("DataDeInicio");

                    b.Property<string>("Nome")
                        .IsRequired();

                    b.Property<int>("Periodo");

                    b.Property<int>("SecretariaId");

                    b.Property<int>("TipoCurso");

                    b.HasKey("Id");

                    b.HasIndex("CoordenadorId");

                    b.HasIndex("SecretariaId");

                    b.ToTable("Cursos");
                });

            modelBuilder.Entity("Mateus.SistemaAcademico.Models.Disciplina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<TimeSpan>("CargaHoraria");

                    b.Property<string>("Nome")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Disciplinas");
                });

            modelBuilder.Entity("Mateus.SistemaAcademico.Models.Frequencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AlunoId");

                    b.Property<DateTime>("Data");

                    b.Property<int>("DisciplinaId");

                    b.Property<int>("TipoFrequencia");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId");

                    b.HasIndex("DisciplinaId");

                    b.ToTable("Frequencias");
                });

            modelBuilder.Entity("Mateus.SistemaAcademico.Models.Joins.CursoDisciplina", b =>
                {
                    b.Property<int>("CursoId");

                    b.Property<int>("DisciplinaId");

                    b.HasKey("CursoId", "DisciplinaId");

                    b.HasIndex("DisciplinaId");

                    b.ToTable("CursoDisciplina");
                });

            modelBuilder.Entity("Mateus.SistemaAcademico.Models.Joins.ProfessorCurso", b =>
                {
                    b.Property<int>("ProfessorId");

                    b.Property<int>("CursoId");

                    b.HasKey("ProfessorId", "CursoId");

                    b.HasIndex("CursoId");

                    b.ToTable("ProfessorCurso");
                });

            modelBuilder.Entity("Mateus.SistemaAcademico.Models.Joins.ProfessorDisciplina", b =>
                {
                    b.Property<int>("ProfessorId");

                    b.Property<int>("DisciplinaId");

                    b.HasKey("ProfessorId", "DisciplinaId");

                    b.HasIndex("DisciplinaId");

                    b.ToTable("ProfessorDisciplina");
                });

            modelBuilder.Entity("Mateus.SistemaAcademico.Models.Professor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cpf")
                        .IsRequired();

                    b.Property<DateTime>("DataDeNascimento");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("Nome")
                        .IsRequired();

                    b.Property<string>("Titulacao")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Professor");
                });

            modelBuilder.Entity("Mateus.SistemaAcademico.Models.Responsavel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cpf")
                        .IsRequired();

                    b.Property<DateTime>("DataDeNascimento");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<int>("Escolaridade");

                    b.Property<int>("EstadoCivil");

                    b.Property<string>("Nome")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Responsavel");
                });

            modelBuilder.Entity("Mateus.SistemaAcademico.Models.Secretaria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cpf")
                        .IsRequired();

                    b.Property<DateTime>("DataDeNascimento");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("Nome")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Secretarias");
                });

            modelBuilder.Entity("Mateus.SistemaAcademico.Models.Telefone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AdministradorId");

                    b.Property<int?>("AlunoId");

                    b.Property<int>("Numero");

                    b.Property<int?>("ProfessorId");

                    b.Property<int?>("ResponsavelId");

                    b.Property<int?>("SecretariaId");

                    b.Property<int>("TipoTelefone");

                    b.HasKey("Id");

                    b.HasIndex("AdministradorId");

                    b.HasIndex("AlunoId");

                    b.HasIndex("ProfessorId");

                    b.HasIndex("ResponsavelId");

                    b.HasIndex("SecretariaId");

                    b.ToTable("Telefones");
                });

            modelBuilder.Entity("Mateus.SistemaAcademico.Models.TipoDeAvaliacoes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AlunoId");

                    b.Property<DateTime>("DataAvaliacao");

                    b.Property<int>("DisciplinaId");

                    b.Property<float>("NotaAvaliacoes");

                    b.Property<float>("NotaExameFinal");

                    b.Property<float>("NotaSubstitutivas");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId");

                    b.HasIndex("DisciplinaId");

                    b.ToTable("TipoDeAvaliacoes");
                });

            modelBuilder.Entity("Mateus.SistemaAcademico.Models.Trabalho", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AlunoId");

                    b.Property<DateTime>("DataDaEntrega");

                    b.Property<DateTime>("DataDeInicio");

                    b.Property<int>("DisciplinaId");

                    b.Property<float>("NotaDoTrabalho");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId");

                    b.HasIndex("DisciplinaId");

                    b.ToTable("Trabalhos");
                });

            modelBuilder.Entity("Mateus.SistemaAcademico.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Login")
                        .IsRequired();

                    b.Property<string>("Senha")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Mateus.SistemaAcademico.Endereco", b =>
                {
                    b.HasOne("Mateus.SistemaAcademico.Models.Administrador")
                        .WithMany("Enderecos")
                        .HasForeignKey("AdministradorId");

                    b.HasOne("Mateus.SistemaAcademico.Models.Aluno")
                        .WithMany("Enderecos")
                        .HasForeignKey("AlunoId");

                    b.HasOne("Mateus.SistemaAcademico.Models.Professor")
                        .WithMany("Enderecos")
                        .HasForeignKey("ProfessorId");

                    b.HasOne("Mateus.SistemaAcademico.Models.Responsavel")
                        .WithMany("Enderecos")
                        .HasForeignKey("ResponsavelId");

                    b.HasOne("Mateus.SistemaAcademico.Models.Secretaria")
                        .WithMany("Enderecos")
                        .HasForeignKey("SecretariaId");
                });

            modelBuilder.Entity("Mateus.SistemaAcademico.Models.Aluno", b =>
                {
                    b.HasOne("Mateus.SistemaAcademico.Models.Curso", "Curso")
                        .WithMany("Alunos")
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Mateus.SistemaAcademico.Models.Disciplina")
                        .WithMany("Alunos")
                        .HasForeignKey("DisciplinaId");

                    b.HasOne("Mateus.SistemaAcademico.Models.Responsavel", "Responsavel")
                        .WithMany("Alunos")
                        .HasForeignKey("ResponsavelId1");
                });

            modelBuilder.Entity("Mateus.SistemaAcademico.Models.Conteudo", b =>
                {
                    b.HasOne("Mateus.SistemaAcademico.Models.Disciplina", "Disciplina")
                        .WithMany("Conteudo")
                        .HasForeignKey("DisciplinaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Mateus.SistemaAcademico.Models.Curso", b =>
                {
                    b.HasOne("Mateus.SistemaAcademico.Models.Professor", "Coordenador")
                        .WithMany()
                        .HasForeignKey("CoordenadorId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Mateus.SistemaAcademico.Models.Secretaria", "Secretaria")
                        .WithMany("Cursos")
                        .HasForeignKey("SecretariaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Mateus.SistemaAcademico.Models.Frequencia", b =>
                {
                    b.HasOne("Mateus.SistemaAcademico.Models.Aluno", "Aluno")
                        .WithMany()
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Mateus.SistemaAcademico.Models.Disciplina", "Disciplina")
                        .WithMany()
                        .HasForeignKey("DisciplinaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Mateus.SistemaAcademico.Models.Joins.CursoDisciplina", b =>
                {
                    b.HasOne("Mateus.SistemaAcademico.Models.Curso", "Curso")
                        .WithMany("Disciplina")
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Mateus.SistemaAcademico.Models.Disciplina", "Disciplina")
                        .WithMany("Curso")
                        .HasForeignKey("DisciplinaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Mateus.SistemaAcademico.Models.Joins.ProfessorCurso", b =>
                {
                    b.HasOne("Mateus.SistemaAcademico.Models.Curso", "Curso")
                        .WithMany("Professor")
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Mateus.SistemaAcademico.Models.Professor", "Professor")
                        .WithMany("Curso")
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Mateus.SistemaAcademico.Models.Joins.ProfessorDisciplina", b =>
                {
                    b.HasOne("Mateus.SistemaAcademico.Models.Disciplina", "Disciplina")
                        .WithMany("Professors")
                        .HasForeignKey("DisciplinaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Mateus.SistemaAcademico.Models.Professor", "Professor")
                        .WithMany("Disciplinas")
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Mateus.SistemaAcademico.Models.Telefone", b =>
                {
                    b.HasOne("Mateus.SistemaAcademico.Models.Administrador")
                        .WithMany("Telefones")
                        .HasForeignKey("AdministradorId");

                    b.HasOne("Mateus.SistemaAcademico.Models.Aluno")
                        .WithMany("Telefones")
                        .HasForeignKey("AlunoId");

                    b.HasOne("Mateus.SistemaAcademico.Models.Professor")
                        .WithMany("Telefones")
                        .HasForeignKey("ProfessorId");

                    b.HasOne("Mateus.SistemaAcademico.Models.Responsavel")
                        .WithMany("Telefones")
                        .HasForeignKey("ResponsavelId");

                    b.HasOne("Mateus.SistemaAcademico.Models.Secretaria")
                        .WithMany("Telefones")
                        .HasForeignKey("SecretariaId");
                });

            modelBuilder.Entity("Mateus.SistemaAcademico.Models.TipoDeAvaliacoes", b =>
                {
                    b.HasOne("Mateus.SistemaAcademico.Models.Aluno", "Aluno")
                        .WithMany()
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Mateus.SistemaAcademico.Models.Disciplina", "Disciplina")
                        .WithMany()
                        .HasForeignKey("DisciplinaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Mateus.SistemaAcademico.Models.Trabalho", b =>
                {
                    b.HasOne("Mateus.SistemaAcademico.Models.Aluno", "Aluno")
                        .WithMany()
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Mateus.SistemaAcademico.Models.Disciplina", "Disciplina")
                        .WithMany()
                        .HasForeignKey("DisciplinaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
